apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsmc-web-app
  labels:
    app: tsmc-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsmc-web-app
  template:
    metadata:
      labels:
        app: tsmc-web-app
      annotations: # <--- 新增 Prometheus Annotation
          prometheus.io/scrape: "true" # 告訴 Prometheus 抓取這個 Pod
          prometheus.io/port: "8080"  # 告訴 Prometheus 抓取這個端口
          prometheus.io/path: "/metrics" # 告訴 Prometheus 抓取這個路徑
    spec:
      containers:
      - name: tsmc-web-app
        # 請將 <使用者名稱> 和 <儲存庫名稱> 替換為你的 GHCR 路徑
        image: ghcr.io/vf19961226/tsmc-devops-app:latest
        ports:
        - containerPort: 8080 # 必須與 Dockerfile 中 EXPOSE 的端口一致
      imagePullSecrets: # <--- 新增這行
      - name: ghcr-secret # <--- 使用你剛才創建的 Secret 名稱